python ./scripts/evaluate.py FocalClick\
  --model_dir=./experiments/brats/segformerB3/000_FocalClick-SegFormerB3/checkpoints/\
  --checkpoint=epoch-19-val-loss-1.28.pth\
  --infer-size=96\
  --datasets=BraTS_Val\
  --datapath=./data/datasets/BraTS\
  --channel=flair\
  --label=wt\
  --cpu\
  --target-iou=0.95\
  --n-clicks=20\
  --thresh=0.5\
  --print-ious\
  --vis
